networks:
  vet-network:
    driver: bridge

# Общие переменные окружения для Java-сервисов
x-java-env: &java-env
  SPRING_PROFILES_ACTIVE: docker
  DB_HOST: ${REMOTE_HOST:-postgres}
  DB_PORT: ${REMOTE_HOST:+5432}
  SPRING_DATASOURCE_URL: jdbc:postgresql://${REMOTE_HOST:-postgres}:5432/vet-clinic
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: 12345
  MONGO_HOST: ${REMOTE_HOST:-mongo}
  MONGO_PORT: 27017
  REDIS_HOST: ${REMOTE_HOST:-redis}
  REDIS_PORT: 6379
  KEYCLOAK_ISSUER_URI: http://${REMOTE_HOST:-keycloak}:8080/realms/clinic-realm

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vet-clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5010:5432"      # открываем порт для доступа с ноутбука
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - vet-network
    profiles: ["infra"]   # запускается только на ПК

  mongo:
    image: mongo:7.0
    ports:
      - "5020:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - vet-network
    profiles: ["infra"]

  redis:
    image: redis:7.2-alpine
    ports:
      - "5030:6379"
    networks:
      - vet-network
    profiles: ["infra"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "5040:9000"
      - "5041:9001"
    volumes:
      - minio-data:/data
    networks:
      - vet-network
    profiles: ["infra"]

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    networks:
      - vet-network
    # profiles: ["infra"]

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/vet-clinic
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 12345
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: 192.168.1.114  # текущий IP ПК
      KC_HOSTNAME_STRICT: false
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - vet-network
    profiles: ["infra"]

  python-ai:
    build: ./services/ai-model
    ports:
      - "8091:8091"
    environment:
      MODEL_PATH: /app/pet_health_model.pkl
      REDIS_HOST: ${REMOTE_HOST:-redis}
    volumes:
      - ./services/ai-model:/app
    networks:
      - vet-network
    profiles: ["infra"]

  # ---------- МИКРОСЕРВИСЫ (по умолчанию на ПК, но могут быть запущены и локально) ----------
  appointment:
    build: ./services/appointment-service
    ports:
      - "8081:8081"
    environment:
      <<: *java-env
      KEYCLOAK_CLIENT_SECRET: KndP9iogTlX3TrdkzuPWgZYzztsp9o8D
      KEYCLOAK_EXTRA_ISSUER_URL: http://keycloak:8080/realms/clinic-realm
      TG_BOT_HOST: ${REMOTE_HOST:-telegram-bot}
      TG_BOT_PORT: 8090
    depends_on:
      - postgres
      - redis
      - keycloak
    networks:
      - vet-network
    profiles: ["infra"]   # можно запустить и там, и там (но обычно на ПК)

  management:
    build: ./services/management-service
    ports:
      - "8082:8082"
    environment:
      <<: *java-env
      KEYCLOAK_CLIENT_SECRET: your-management-secret
    depends_on:
      - postgres
      - redis
      - keycloak
    networks:
      - vet-network
    profiles: ["infra"]

  profile:
    build: ./services/profile-service
    ports:
      - "8083:8083"
    environment:
      <<: *java-env
      KEYCLOAK_CLIENT_SECRET: your-profile-secret
    depends_on:
      - mongo
      - keycloak
    networks:
      - vet-network
    profiles: ["infra"]

  pet-health-analyzer:
    build: ./services/pet-health-analyzer-service
    ports:
      - "8084:8084"
    environment:
      <<: *java-env
      KEYCLOAK_CLIENT_SECRET: KndP9iogTlX3TrdkzuPWgZYzztsp9o8D
      MQTT_HOST: ${REMOTE_HOST:-mqtt}
      MQTT_PORT: 1883
      GATEWAY_HOST: ${REMOTE_HOST:-vet-gateway}
      GATEWAY_PORT: 8888
      PYTHON_HOST: ${REMOTE_HOST:-python-ai}
      PYTHON_PORT: 8091
      MINIO_HOST: ${REMOTE_HOST:-minio}
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - postgres
      - mongo
      - redis
      - keycloak
      - mqtt
      - python-ai
    networks:
      - vet-network
    profiles: ["infra"]

  pet-wearable:
    build: ./services/petwearable-service
    ports:
      - "8085:8085"
    environment:
      <<: *java-env
      KEYCLOAK_CLIENT_SECRET: your-petwearable-secret
      MQTT_HOST: ${REMOTE_HOST:-mqtt}
      MQTT_PORT: 1883
      GATEWAY_HOST: ${REMOTE_HOST:-vet-gateway}
      GATEWAY_PORT: 8888
    depends_on:
      - postgres
      - redis
      - keycloak
    networks:
      - vet-network
    profiles: ["infra"]

  telegram-bot:
    build: ./services/telegram-bot-service
    ports:
      - "8090:8090"
    environment:
      <<: *java-env
      KEYCLOAK_CLIENT_SECRET: MnRm2WcQMWruSA09qH2jpL9dwwF45ijx
      BOT_TOKEN: ${BOT_TOKEN:-7837490236:AAFYka05fv1LDRseAdcJ3E_n_GxiGI3pOtA}
      BOT_WEBHOOK_URL: ${BOT_WEBHOOK_URL:-https://jpr3ta-109-174-76-92.ru.tuna.am}
      JETTY_HOST: localhost
      JETTY_PORT: 9091
      MQTT_HOST: ${REMOTE_HOST:-mqtt}
      MQTT_PORT: 1883
      GATEWAY_HOST: ${REMOTE_HOST:-vet-gateway}
      GATEWAY_PORT: 8888
    depends_on:
      - postgres
      - keycloak
      - mqtt
    networks:
      - vet-network
    profiles: ["infra"]

  vet-gateway:
    build: ./services/vet-gateway
    ports:
      - "8888:8888"
    environment:
      <<: *java-env
      KEYCLOAK_CLIENT_SECRET: oy3FdqCED7Wi4BPX7JZ0Y3ils24UopsR
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/clinic-realm
      KEYCLOAK_HOST: ${REMOTE_HOST:-keycloak}
      KEYCLOAK_PORT: 8080

      APPOINTMENT_HOST: ${REMOTE_HOST:-appointment}
      APPOINTMENT_PORT: 8081

      MANAGEMENT_HOST: ${REMOTE_HOST:-management}
      MANAGEMENT_PORT: 8082

      PROFILE_HOST: ${REMOTE_HOST:-profile}
      PROFILE_PORT: 8083
      
      TELEGRAM_HOST: ${REMOTE_HOST:-telegram-bot}
      TELEGRAM_PORT: 8090
    depends_on:
      - management
      - profile
      - keycloak
    networks:
      - vet-network
    profiles: ["infra"]

  # ---------- ФРОНТЕНД (чаще всего запускается локально) ----------
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: HLZUx8ifGW+9pT1Xh0v7tln8706sYj+++i2DSXxbruY=
      KEYCLOAK_ISSUER: http://${REMOTE_HOST:-keycloak}:8080/realms/clinic-realm
      KEYCLOAK_CLIENT_ID: vet-frontend
      KEYCLOAK_CLIENT_SECRET: Gv1nqQU8imIrxFxQrI9N7Dk0RZqiZ5lQ
      KEYCLOAK_ADMIN_CLIENT_ID: profile-service
      KEYCLOAK_ADMIN_CLIENT_SECRET: Xl2WP6TD01qkB5Lmd5abECck6VxlGBtk
      KEYCLOAK_REALM: clinic-realm
      KEYCLOAK_BASE_URL: http://${REMOTE_HOST:-keycloak}:8080
      NEXT_PUBLIC_API_URL: http://${REMOTE_HOST:-vet-gateway}:8888
      API_URL_EXTERNAL: http://${REMOTE_HOST:-localhost}:8888
    # depends_on:
    #   - vet-gateway
    #   - keycloak
    networks:
      - vet-network
    profiles: ["dev"]   # по умолчанию только на ноутбуке

volumes:
  postgres-data:
  mongo-data:
  minio-data: